name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v5

      - name: Bei GHCR anmelden
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tests ausführen
        run: ./tests/test.sh

      - name: Docker Image bauen
        run: docker build -t devops-day34 docker/day23

      - name: Docker Image taggen
        run: docker tag devops-day34:latest ghcr.io/landro82/devops-kurs:day35
     
      - name: Docker Image pushen
        run: docker push ghcr.io/landro82/devops-kurs:day35  
